// pages/api/frases.js

const frases = {
  general: [
    "A vida é feita de escolhas.",
    "O melhor ainda está por vir.",
    "Nunca desista dos seus sonhos.",
    "Tudo acontece no tempo certo.",
    "Acredite no poder do agora.",
    "Você é mais forte do que pensa.",
    "O sucesso começa com a decisão de tentar.",
    "A felicidade é um estado de espírito.",
    "A simplicidade é o segredo da felicidade.",
    "A jornada é tão importante quanto o destino.",
    
  ],
  names: [
    "que a vida te sorria sempre!",
    "O melhor está por vir.",
    "nunca pare de sonhar!",
    "Que sua jornada seja incrível.",
    "que a felicidade te acompanhe sempre!",
    "O futuro é todo seu.",
    "que seus dias sejam repletos de alegria!",
    "que suas conquistas sejam muitas.",
    "acredite sempre no melhor.",
    "Que a felicidade te acompanhe sempre.",
  
  ],

  Parameuamor: [
    "te amo.",
    "Você é tudo pra mim!",
    "Você nunca vai precisar se sentir só"],

  celebrations: [
    "Parabéns! Que seu dia seja tão incrível quanto você.",
    "Feliz aniversário! Que seus sonhos se realizem.",
    "Parabéns por mais um ano de vida, que venham muitos outros.",
    "Hoje é seu dia! Aproveite cada momento.",
    "Feliz aniversário! Que a alegria nunca te falte.",
    "Parabéns! Que sua vida seja cheia de momentos felizes.",
    "Hoje celebramos você! Muitas felicidades.",
    "Feliz aniversário! Que seu caminho seja repleto de luz.",
    "Que sua celebração seja cheia de amor e alegria.",
    "Celebre cada vitória com gratidão e felicidade.",
   
  ],

  Mae: [
    "te amo.",
    "Você é tudo pra mim!",
    "Pedi a Deus que me fizesse feliz, e Ele me tornou mãe.",
    "Uma pela outra",
    "Ser mãe é amar sem fronteiras",
    "Me orgulho de ser mãe, mas me orgulho mais ainda de ter você como filha",
    "O filho mais rico é aquele que tem uma mãe que ora por ele",
    "Ela é forte. Ela é guerreira. Ela é minha mãe.",
    "Filha, seremos sempre nós, por toda a vida. Nunca duvide disso!",
    "Mãe, um título maior que rainha",
    "Eu vi minha mãe lutando, mas nunca vi ela desistindo. Quanto orgulho dessa mulher.",
    "Você é a melhor mãe do mundo",
    "Filha, amor maior do mundo!",
    "Minha filha, eu não te dei o presente da vida, a vida me deu você como presente.",
    "É incrível como algo tão pequenino pode te fazer sentir algo tão grande.",
    " Filhas são como flores que embelezam o nosso mundo com bênçãos.",
    "Não importa o que você diga, não importa o que você faça, não importa onde você esteja. Eu sempre vou te amar minha filha.",
    "Minha filha, você é a razão de eu ser tão forte quanto sou hoje.",
    "Minha filha, a sua alegria é a minha alegria, seu coração faz o meu bater cada dia mais forte.",
    "Uma filha é um ser que chega ao mundo para nos fazer entender como é amar alguém mais intensamente do que a nós mesmos.",
    "Minha filha, eu só acredito em amor à primeira vista, pois desde o primeiro momento que te vi, já sabia que te amaria pelo resto da minha vida.",
    "Uma mãe é sempre a melhor amiga de sua filha.",
    "O tesouro de uma mãe é sempre a sua filha querida.",
    "Uma filha é uma menina que cresce para se tornar a sua melhor e mais estimada amiga.",
     "A felicidade verdadeira é o tempo compartilhado entre uma mãe e uma filha.",
     "Mãe: um título de nobreza acima de rainha para quem tem uma princesa em seus braços.",
     "Ter uma filha é a forma como Deus nos diz: você terá uma amiga verdadeira pelo resto de sua vida.",
     "O amor entre mãe e filha é um amor eterno e incondicional.",
     "Sou a mãe mais feliz deste mundo por ter uma filha como você ao meu lado.",
     "Não importa a idade que você tenha, às vezes o que uma filha mais precisa é do colo de sua mãe.",
     "A vida não lhe dá um manual, ela lhe entrega uma mãe.",
     " Mães e filhas se tornam ainda mais próximas quando as filhas se tornam mães.",
     "Mães e filhas nunca se distanciam, talvez isso aconteça pela distância, mas nunca pelo coração.",
     "Um dia, quando as páginas da minha vida terminarem, a minha filha será o meu capítulo mais bonito.",
     "O amor entre uma mãe e uma filha está sempre gravado em seus respectivos corações.",
     "De todas as coisas que as minhas mãos já tocaram, você é de longe a mais especial.",
     "A minha maior felicidade é o tempo que compartilho com você minha filha.",
  ],

  
  inspirational: [
    "Acredite em si mesmo, tudo é possível.",
    "Você pode tudo, basta querer.",
    "Não tenha medo de tentar, o sucesso vem com a coragem.",
    "O impossível é só uma questão de perspectiva.",
    "A persistência transforma sonhos em realidade.",
    "O maior erro é não tentar.",
    "O único limite que você tem é aquele que você coloca em sua mente.",
    "Seu único obstáculo é você mesmo.",
    "Acredite no seu potencial, você é capaz de grandes coisas.",
    "Grandes sonhos começam com pequenos passos.",
    
  ],

  love: [
    "O amor é a maior força do universo.",
    "Amar é dar asas ao outro sem nunca prendê-lo.",
    "O coração fala a linguagem que nenhuma palavra pode traduzir.",
    "Amar é encontrar o paraíso em um sorriso.",
    "O verdadeiro amor é aquele que cresce todos os dias.",
    "O amor é a chave para todas as portas da felicidade.",
    "Não há limites para o poder de um amor genuíno.",
    "Quando há amor, tudo é possível.",
    "O amor transforma o comum em extraordinário.",
    "Um coração cheio de amor é invencível",
    "Você completa a minha vida, enche o meu coração de alegria e será para sempre o meu eterno amor.",
    "Meu amor, você está em meus pensamentos do momento que acordo até a hora que eu vou dormir.",
    "Estar ao seu lado é a minha maior felicidade. Eu te amo incondicionalmente, meu amor.",
    "Que sorte eu tive de ter cruzado seu caminho e roubado seu coração.",
    "Eu amo tudo em você: seu sorriso, sua voz e até suas manias. Eu te amo assim, meu amor: por completo.",
    "Todo dia é um dia feliz se estou ao seu lado.",
    "Você me inspira, nutre o meu coração e me enche de alegria. Eu te amo, meu amor.",
    "Amar é sentir um turbilhão de sentimentos ao mesmo tempo e, dentro de mim, um universo inteiro se expande pelo seu amor",
    "Creio que a escolha de amar é sem dúvidas a mais poderosa força do universo. Me sinto completa ao seu lado, meu amor.",
    "Amar é entender que somos dois indivíduos que decidiram compartilhar uma vida em comum.",
    "Se do meu amor por você nascesse uma flor, eu poderia caminhar eternamente por um jardim infinito.",
    "Eu só entendi o que era o amor quando você entrou na minha vida e deu sentido a ela.",
    "O meu amor por você não cabe no meu coração. Ele transborda o meu ser e completa a minha alma.",
  ],


  friendship: [
    "A amizade é o maior presente da vida.",
    "Amigos são a família que escolhemos.",
    "Um amigo verdadeiro é um tesouro raro.",
    "A amizade torna os bons momentos ainda melhores.",
    "A distância nunca separa amigos de verdade.",
    "Ter um amigo é nunca estar sozinho.",
    "Amizade é a base para qualquer relação duradoura.",
    "Rir com amigos é o melhor remédio.",
    "Amizade é compartilhar a jornada da vida.",
    "Amigos tornam o mundo mais bonito.",
   
  ],
  motivational: [
    "Você é mais forte do que pensa.",
    "Acredite, você pode alcançar o impossível.",
    "Cada passo para frente é uma vitória.",
    "Seja a mudança que deseja ver no mundo.",
    "A vida recompensa quem se esforça.",
    "Pequenos progressos levam a grandes conquistas.",
    "Nunca pare de aprender e crescer.",
    "A jornada pode ser longa, mas vale a pena.",
    "O sucesso é construído com esforço diário.",
    "Você é capaz de superar qualquer desafio.",
    "Não duvide de você.",
    "se prepare pra vencer.",
    "O que não te desafia não te transforma. Crescer dói, mas vale a pena.",
    "Não se misture com quem você não seria.",
    "No lugar certo, você brilha diferente.",
    "Seja 1% melhor todos os dias",
    "sua atitude define tudo",
    "Apenas comece.",
    "Tarde foi ontem, hoje ainda dá tempo.",
    "O básico bem feito é perfeito",
    "Calma, tudo tem seu tempo",
    "Quanto mais você é, menos precisa dizer que é.",
    "Ou você faz, ou você assiste o outro fazer.",
    "Disciplina é fazer o que você não quer, para ter o que quer.",
    "Quem investe na fé, não precisa contar com a sorte",
    "Não fala, vai lá e faz!",
    "Não pare até sentir orgulho de você",
    "Inspire o mundo ao seu redor",
   
  ],
  spiritual: [
    "A fé move montanhas.",
    "O universo conspira a favor de quem acredita.",
    "A paz interior começa com a gratidão.",
    "Deus tem um plano para cada um de nós.",
    "A espiritualidade é a conexão com o divino dentro de você.",
    "A luz divina está sempre presente.",
    "Confie no processo divino da vida.",
    "Sua alma conhece o caminho, siga-a.",
    "A serenidade vem da conexão com o espírito.",
    "Cada dia é uma bênção para agradecer.",
    "jovens seguindo a cristo"
   
  ],
  welcome: [
    "Bem-vindo! Que sua jornada seja incrível.",
    "É um prazer ter você aqui!",
    "Que sua chegada traga alegria a todos nós.",
    "Bem-vindo ao início de algo maravilhoso.",
    "Que este seja o começo de grandes conquistas.",
    "Sua presença faz toda a diferença.",
    "Bem-vindo! Estamos ansiosos para compartilhar este momento com você.",
    "Aqui você encontrará um lar longe de casa.",
    "Bem-vindo! Que este lugar seja especial para você.",
    "Sua chegada ilumina o ambiente. Bem-vindo!",
   
  ],
  farewell: [
    "Despedidas são apenas um até logo.",
    "Leve consigo todas as boas memórias.",
    "Sentiremos sua falta, mas desejamos tudo de melhor para você.",
    "Que este novo capítulo seja incrível.",
    "Você deixa um vazio que ninguém poderá preencher.",
    "Até breve! Que sua jornada seja brilhante.",
    "As despedidas são o início de novas aventuras.",
    "Você sempre terá um lugar especial aqui.",
    "Boa sorte em sua nova jornada!",
    "A distância nunca apagará as boas lembranças.",
   
  ],
  gratitude: [
    "Obrigado por fazer a diferença em minha vida.",
    "Sua gentileza é inesquecível.",
    "Sou grato por tudo o que você fez.",
    "A gratidão transforma o comum em extraordinário.",
    "Obrigado por sempre estar lá por mim.",
    "Cada gesto seu significa muito.",
    "Sou imensamente grato pela sua amizade.",
    "Agradeço por cada momento especial que compartilhamos.",
    "Obrigado por ser uma luz em minha vida.",
    "A gratidão é a memória do coração. Obrigado!",
  
  ],
};

export default function handler(req, res) {
  const { category } = req.query;

  if (!category || !frases[category]) {
    return res.status(400).json({ error: "Categoria inválida ou não especificada" });
  }

  res.status(200).json(frases[category]);
}
